#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer.

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # Check if the given command is installed, if not, install it
    # Suppress output with -qq option for quiet installation
    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up HAProxy...\n"

# Backup default HAProxy server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# HAProxy server configuration
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 238053-web-01 100.25.220.119 check
    server 238053-web-02 100.25.147.34 check
"

# Apply the server configuration to the HAProxy config file
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Start or restart HAProxy service based on its status
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

# Output server names
echo "Server names configured: 238053-web-01, 238053-web-02"
