#!/usr/bin/env bash
#Displays numbers from 1 to 100 and FizzBuzz, Fizz or Buzz if it's a multiple of 3, 5 or both

for ((i=1; i<=100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
