#!/usr/bin/env bash
#Displays 20 numbers but with bad luck from China, Japan nd Italy on the 4th, 9th and 17th iterations respectively

count=1

while [ $count -le 20 ]
do
  case $count in
    4)
      echo "$count"
      echo "bad luck from China"
      ;;
    9)
      echo "$count"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$count"
      echo "bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  ((count++))
done
