#!/usr/bin/env bash
#Displays content of the current directory in a list

echo "Content of the current directory:"
for file in *; do
    if [[ ! -f $file ]]; then
        continue
    fi
    filename=$(echo $file | cut -d '-' -f2-)
    echo "$filename"
done
